### PR TITLE
Add rust program

### PR DESCRIPTION
**Pull request by shssoichiro**

### CODE REVIEW

**Comment by shssoichiro** [comment]
Program                                |Time   |User   |Memory
---------------------------------------|-------|-------|------
rust/wordcount/wordcount               |5.57   |5.42   |331796
cpp/wc_vector                          |8.73   |8.55   |249004
python/wordcount_py2gabor.py           |8.82   |8.60   |248076
go/bin/wordcount                       |10.72  |10.40  |373672
php7.0 php/wordcount.php               |12.76  |9.71   |267480
cpp/wc_hash_nosync                     |14.55  |11.73  |331748
python/wordcount_py2.py                |15.48  |15.22  |562284
cpp/wc_baseline_hash                   |19.70  |16.69  |348032
java -classpath java WordCount         |21.16  |15.22  |390400
java -classpath java WordCountEntries  |23.32  |17.48  |385488
python/wordcount_py3.py                |22.51  |22.12  |489888
mono csharp/WordCountList.exe          |22.52  |16.44  |339872
nodejs javascript/wordcount.js         |27.47  |27.24  |382264
cpp/wc_baseline                        |27.62  |24.45  |361000
perl/wordcount.pl                      |27.87  |27.49  |452288
php5.6 php/wordcount.php               |29.50  |26.19  |790452
nodejs javascript/wordcount2.js        |34.19  |30.78  |360316
julia julia/wordcount.jl               |39.55  |39.26  |524948
haskell/WordCount                      |50.89  |50.21  |1059788
bash/wordcount.sh                      |66.16  |65.32  |8952

**Comment by juditacs** [comment]
It's very impressive, thank you. I'm a Rust fan now.

It's almost twice as fast as the best C++, I'll update the results soon.

There are two errors while installing rust:

~~~
rustup: command failed: curl -s -f -O https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256
rustup: couldn't download checksum file 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'
~~~

**Comment by shssoichiro** [comment]
Those errors can safely be ignored. I'm uncertain if Rust has perhaps changed the way they do checksums and hasn't updated their installer (the error is from that sha256 checksum file being 404), but it looks like the installer falls back to a sha1 checksum and the install still completes.

**Comment by juditacs** [comment]
Is this parallel by default? If so, it should be listed in a separate leaderboard.

**Comment by shssoichiro** [comment]
No, this is single-threaded by default.

**Pull request merged**
