### PR TITLE
c implementation

### PR DESCRIPTION
**Pull request by gaebor**
The main advantage of the C is the scanf and printf, they are faster than cin and cout and the I/O is definitely the bottleneck.
I used a custom hash table, it may not be the most efficient.
Tested with gcc 4.7.2 (x86_64) and VS2013 (Win32 and x64)

### CODE REVIEW

**Comment by juditacs** [comment]
There is a wordcount.cpp in your commits.

**Comment by gaebor** [comment]
Sry I didn't want to create two pull requests for this. I also worked on the cpp implementation.

**Comment by juditacs** [comment]
I'm in the middle of renaming the cpp implementations. Can you withhold it for a little while?

**Comment by gaebor** [comment]
How do I do that?

**Comment by juditacs** [comment]
If you update your branch, this PR will be updated as well. You can create a branch than git rm the cpp file on your master branch.

**Comment by juditacs** [comment]
Oh, and please do create a new PR for the cpp file.

**Comment by juditacs** [comment]
I'm done renaming everything except the javascript sources. Go ahead and improve cpp.

I also ordered alphabetically run_commands.txt and binary_mapping.txt, you might have conflicts.

**Comment by gaebor** [comment]
Is there any particular reason you don't merge this PR?

**Comment by juditacs** [comment]
Yes. There are unresolved conflicts. It turns green is everything is resolved and automatic merge is possible.

I changed some stuff today. https://github.com/juditacs/wordcount#adding-a-new-program

**Pull request merged**
