### PR TITLE
Counter instead of defaultdict

### PR DESCRIPTION
**Pull request by DavidNemeskey**
Unfortunately `counter.most_common()` doesn't work, because it doesn't order by the keys. :(

### CODE REVIEW

**Comment by juditacs** [comment]
I knew about counter and I don't see how it is an improvement. Is it faster?

**Comment by DavidNemeskey** [comment]
Well, if you want to count something, you use a counter, right? :) I didn't do any measurements.

**Comment by yedpodtrzitko** [comment]
using `Counter` seems to be slower

**Comment by juditacs** [comment]
I though so. Can I close this?

**Comment by yedpodtrzitko** [comment]
yes

**Comment by juditacs** [comment]
I was asking @DavidNemeskey :)

**Comment by yedpodtrzitko** [comment]
oh ok .)

**Comment by DavidNemeskey** [comment]
BTW apparently in Python 3.4+, `Counter` is faster than `defaultdict`...

**Pull request closed without merging**
