### PR TITLE
Improved Java version

### PR DESCRIPTION
**Pull request by sgwerder**
Improved Java version. Replaced TreeMap with normal HashMap which seems to be faster in my tests. Needs to be reviewed though.

### CODE REVIEW

**Comment by juditacs** [comment]
Thanks for the contribution.

The tests pass but it seems a bit slower than the previous version. I tested it on 5 million lines from Wikipedia:

| Rank | Experiment | CPU seconds | User time | Maximum memory |
| :---: | :---: | :---: | :---: | :---: |
| 1 | old: java -classpath java WordCount | 138.67 | 124.51 | 1828216 |
| 2 | old: java -classpath java WordCountEntries | 138.83 | 124.07 | 1812116 |
| 3 | new: java -classpath java WordCount | 145.83 | 126.45 | 1855408 |

**Comment by sgwerder** [comment]
Ahh I was testing with the provided test cases only.

**Comment by juditacs** [comment]
Ok, I'll close this PR but feel free to open a new one if you have an improved one. BTW I wrote a follow-up post about this challenge: http://juditacs.github.io/2016/03/19/wordcount2.html

**Comment by sgwerder** [comment]
Now this is getting weird. I was just testing with the Hungarian wiki xml (121 MB) from the create_input.sh, but measuring running time without JVM startup. The old one's running around 8.5 seconds and my new one at 7.5 seconds. Can I ask you what you've been testing with to get 120'ish usertime ?

**Comment by juditacs** [comment]
I'm testing on the Hungarian Wikipedia, not Wikisource. I should change that in the script, thanks for pointing it out.
I include JVM startup. How do you measure it?

**Comment by sgwerder** [comment]
I measure at runtime and have the different versions run consecutively. I figured, that the first run will always be slower than the rest, thats probably because of some String caching or JVM hotpath magic. So I run a couple of versions before I actually measure.
Anyway, I made another version using fastutil lib :) should be around 6.8 seconds compared to 7.5 seconds / 8.5 seconds (Is it allowed to upload a lib replacing standard lib?). Could you post a link to the Hungarian Wikipedia file you use to measure, so I can test this in action before making another Pull Request?

**Comment by juditacs** [comment]
http://dumps.wikimedia.org/huwiki/latest/huwiki-latest-pages-meta-current.xml.bz2

I think the whole process should be included in the measurement. Do you think that separate JVMs might run faster after the first run?

**Comment by sgwerder** [comment]
> I think the whole process should be included in the measurement.

Yes I agree, the whole process should be measured. I only run my tests on the same running JVM for convenience and effectively compare different versions.

>Do you think that separate JVMs might run faster after the first run?

I don't think so.

**Comment by sgwerder** [comment]
Ok, after I gave another try I deem this impossible with Standard lib or going down to byte level reading that I don't want to go into further. It's already choking on reading the 3.6 GB, it doesnt even get to process it.

**Pull request closed without merging**
