### PR TITLE
My new favourite language is go

### PR DESCRIPTION
**Pull request by siklosid**

### CODE REVIEW

**Comment by juditacs** [comment]
It doesn't output anything. It compiles fine but fails all the tests since the outputs are empty.
`./scripts/test_all.sh` runs all tests, `./scripts/test.sh ./go/bin/wordcount` tests go only.

**Comment by siklosid** [comment]
Fixed

**Comment by juditacs** [comment]
It splits on non-breaking space, so test5 fails.

**Comment by siklosid** [comment]
It the readme you wrote that it has to pass at least the first 3 tests.
I fixed it, now it passes test 5 too, but it made the code a little bit ugly.

**Comment by juditacs** [comment]
I'm sorry about that. I'll fix the readme :)

**Comment by juditacs** [comment]
Now it doesn't sort by frequency. I didn't have a test case for this so far, I wrote one now.

**Pull request merged**
