### PR TITLE
Even better javascript

### PR DESCRIPTION
**Pull request by kundralaci**
On 30k lines I got 35-40% improvement.
Use javascript/wordcount.js again, no n+1 files.
Tested, but give it a try.

### CODE REVIEW

**Comment by juditacs** [comment]
Please don't delete wordcount2.js yet.

**Comment by kundralaci** [comment]
Now wordcount2.js is back.

**Comment by juditacs** [comment]
You stripped all the whitespaces from wordcount2.js, but it's better like this.

**Comment by kundralaci** [comment]
Yes, it was an intentional editor setting to remove unnecessary whitespaces.

**Pull request merged**
