### PR TITLE
Add improved php/wordcount implementation

### PR DESCRIPTION
**Pull request by kpeu3i**

### CODE REVIEW

**Comment by juditacs** [comment]
One implementation-per-language is preferred.
There are already two open PRs with PHP improvements (https://github.com/juditacs/wordcount/pull/39 https://github.com/juditacs/wordcount/pull/34), although neither seems finalized. Maybe it would make more sense to work together with them and come up with one common solution.

**Comment by kpeu3i** [comment]
Why everyone can't add his own implementation? You will never find a better solution for a language with those rules.

**Comment by gaebor** [comment]
As long as I know, @juditacs tests every PR before merging. If an implementation is not better than the former, it won't be merged. Try to test your code against the already pulled version.

**Comment by juditacs** [comment]
This is correct. All submissions must pass the tests and outperform the existing one.

**Comment by svanoort** [comment]
I like these criteria, +1.  @kpeu3i  you can also grab competing PRs and compare against them...

**Comment by kpeu3i** [comment]
My implementation successfully passed the tests and it showed better performance (compared with master version) on the small dataset.

**Comment by juditacs** [comment]
If it is indeed better, it can replace the current solution. Please rename your source file to wordcount.php.

**Comment by kpeu3i** [comment]
Done! 

screenshot from 2016-04-08 11 50 03

**Comment by juditacs** [comment]
about 30% improvement, cool.

**Pull request merged**
