### PR TITLE
Added hackyish way of an ETS backed counter

### PR DESCRIPTION
**Pull request by NobbZ**
This improved runtime for the small testset (scripts/create_input.sh) by
50 secs (~120 to ~70) at the cost of some memory, which went from
~1.65GiB to ~1.87GiB.

This is mostly due to the following (assuming OTP 18; its even worse in OTP 17):

* An Elixir `Map` (denoted by `%{}` in source code) uses an erlang map under the hood, which is immutable.
  * This immutability does require copying the whole map on every single update. Even if most references can be reused the time necessary for copying grows linear with the number of entries.
  * Because of some not further explained implemention details of erlangs list even the time necessary for a lookup increases linear with the size of the map.
* To replace it, I've switched over to an Erlang-Term-Storage (known as `ets`).
  * The ETS is a global mutable state and as such discouraged usually in functional languages but fits well into erlangs and elixirs default application structure and design
  * Lookup, insertion and update don't depend on the number of entries in the table, but only on the size of the key

Normaly One would put that module I added into another source-file, but I'm not sure how to do it in a way that source-mapping stays intact.

Apropos sourcemapping. Currently I'm the only one who appears in a `git blame` but @belaustegui did some initial work and also discovered this project. I want to give him also credits. How can we have him back into the list of contributors?

### CODE REVIEW

**Comment by juditacs** [comment]
> Apropos sourcemapping. Currently I'm the only one who appears in a git blame but @belaustegui did some initial work and also discovered this project. I want to give him also credits. How can we have him back into the list of contributors?

He doesn't have any commits regarding the elixir source so we can only list him via additional mapping which I'd like to avoid. He can commit once, then he'll appear in git blame.

**Comment by NobbZ** [comment]
Please don't merge! This became WIP again just a few minutes ago!

**Comment by NobbZ** [comment]
Okay, I fiddled around a little bit more, and in this iteration I was able to break through the one-minute-wall for the file created using `scripts/create_input.sh`:

| Rank | Experiment | CPU seconds | User time | Maximum memory | Contributor |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | rust/wordcount/wordcount | 5.03 | 4.92 | 330580 | Joshua Holmer | 
| 2 | cpp/wordcount | 6.74 | 6.59 | 246788 | Matias Fontanini, Judit Acs | 
| 3 | d/wordcount | 7.3 | 7.2 | 384376 | Pavel Chebotarev | 
| 4 | python/wordcount_py2.py | 7.79 | 7.64 | 245572 | Judit Acs | 
| 5 | go/bin/wordcount | 8.93 | 8.82 | 370400 | David Siklosi | 
| 6 | php7.0 php/wordcount.php | 11.22 | 8.57 | 263152 | Braun Patrik | 
| 7 | python/wordcount_py2_baseline.py | 13.23 | 13.0 | 559448 | Judit Acs | 
| 8 | scala -J-Xmx2g -classpath scala Wordcount | 15.1 | 25.54 | 892824 | Hans van den Bogert | 
| 9 | java -classpath java WordCount | 17.02 | 18.25 | 835948 | Dávid Márk Nemeskey | 
| 10 | mono csharp/WordCountList.exe | 19.3 | 13.94 | 339124 | Peter Szel | 
| 11 | python/wordcount_py3.py | 20.36 | 20.04 | 487452 | Judit Acs | 
| 12 | perl/wordcount.pl | 23.86 | 23.53 | 450392 | Larion Garaczi, Judit Acs | 
| 13 | lua lua/wordcount.lua | 24.37 | 21.63 | 379812 | daurnimator | 
| 14 | cpp/wordcount_baseline | 25.03 | 22.26 | 359580 | Judit Acs | 
| 15 | nodejs javascript/wordcount.js | 25.08 | 24.94 | 380776 | Laci Kundra | 
| 16 | php5.6 php/wordcount.php | 25.64 | 22.68 | 786776 | Braun Patrik | 
| 17 | nodejs typescript/wordcount.js | 30.79 | 28.08 | 353404 | Braun Patrik | 
| 18 | julia julia/wordcount.jl | 33.31 | 33.16 | 508340 | Attila Zseder, getzdan | 
| 19 | java -cp clojure.jar clojure.main clojure/wordcount.clj | 33.55 | 56.66 | 1969924 | lverweijen | 
| 20 | haskell/WordCount | 43.41 | 43.02 | 1057640 | Larion Garaczi | 
| 21 | elixir/wordcount | 59.91 | 58.68 | 1386260 | Norbert Melzer | 
| 22 | bash/wordcount.sh | 60.41 | 68.21 | 11556 | Judit Acs | 

After this got merged, I have a patch ready for the dockerfile which repairs installation of `clojure.jar`!

**Comment by belaustegui** [comment]
The performance gain by using ETS is **awesome**, it pretty much confirms my original suspicions about the creation and destruction of the Map being the primary performance degradation culprit.
In fact, the Scala implementation uses mutable maps instead of the default immutable ones to avoid the same problem we were facing.

The step of reversing the obtained Map to have occurrece numbers as keys and a list of words as values is also great. I've not thought about it when I did the basic implementation, but it has a nice effect on performance.

I'm fascinated about how much I'm learning with all this. Thank you @NobbZ

**Comment by juditacs** [comment]
Cool. Can I take it that this is ready to be merged?

**Comment by NobbZ** [comment]
Yepp, it is.

Judit Acs <notifications@github.com> schrieb am Di., 29. März 2016 09:58:

**Pull request merged**
