### PR TITLE
Add Cuneiform example

### PR DESCRIPTION
**Pull request by joergen7**
Add an example for counting words implemented in the Cuneiform programming language

### CODE REVIEW

**Comment by juditacs** [comment]
The project is discontinued unless somebody volunteers to maintain it.

I have never heard of this language but as far as I can tell your code works on an arbitrary file `sotu/stateoftheunion1790-2014.txt.zip`, and I doubt it would pass all the tests (lowercasing is not required).

**Comment by joergen7** [comment]
It appears, I wasn't aware of the rules section of the README. Is there a chance to have this pr accepted if the requirements are met (even though the project is discontinued)?

**Comment by juditacs** [comment]
The main problem is the Docker image fails to build due to many of the packages being deprecated. I have no way of updating the leaderboard without a working environment. I will accept your PR if it passes all the test, the install commands are in the Dockerfile and build.sh but I can't update the leaderboard.

**Comment by joergen7** [comment]
That is very acceptable.

**Comment by joergen7** [comment]
I will close this pull request and reopen it once the contribution meets all necessary criteria.

**Pull request closed without merging**
