### PR TITLE
Make clojure version more memory efficient

### PR DESCRIPTION
**Pull request by lverweijen**
In #41 it was noted that an input of 5 million gave a memory error.

head -c5000000 works for me now

### CODE REVIEW

**Comment by juditacs** [comment]
It still runs out of memory on my test machine :(

**Comment by lverweijen** [comment]
It finishes for me in the docker image and on my own system. On my own system, it uses 4.2G of RAM according to htop. If less than 4G is required, running it the following way uses 3.3G for me:

```
cat data/huwikisource-latest-pages-meta-current.xml | head -c50000000 | /usr/bin/time java -Xmx1g -classpath clojure.jar clojure.main clojure/wordcount.clj > /dev/null
```

Hopefully, this works for you.

**Comment by juditacs** [comment]
head -c5000000 selects the firs 5M *bytes* of the file instead of the first 5M lines.

**Comment by lverweijen** [comment]
I see, I can now reproduce that error.

**Pull request merged**
