### PR TITLE
Add a Guile Scheme version

### PR DESCRIPTION
**Pull request by ArneBab**
It would be great if you could add this! (this still needs the docker changes: We need to install guile-2.2)

A collaboration of Arne Babenhauserheide and Linus Björnstam.

### CODE REVIEW

**Comment by juditacs** [comment]
Thank you very much.

I'm not ignoring you PR  but I have a lot on my hands right now. I'll fire up the test framework again shortly.

Can you please provide the installation instructions to the Dockerfile (I don't know which package to install exactly)?

**Comment by ArneBab** [comment]
@juditacs Than you for your answer! I’ll add installation instructions in the docker file once I have docker working here so I can actually test it. If you use guile-2.0¹ instead of 2.2, you’ll have roughly 25% longer runtime. But I do not think Ubuntu already provides guile-2.2.

¹: http://packages.ubuntu.com/de/zesty/lisp/guile-2.0

**Comment by juditacs** [comment]
Now that you mention it, the Ubuntu version probably needs updating in the Dockerfile.

**Comment by ArneBab** [comment]
@juditacs I did the change I think the Dockerfile needs to get Guile, but it’s not tested.

**Comment by ArneBab** [comment]
Any update on merging this?

**Comment by juditacs** [comment]
I'm really sorry for the delay. I have some trouble testing it right now so I can't update the leaderboard.

**Comment by ArneBab** [comment]
Don’t worry — time for unpaid work is a luxury we cannot always afford. Thank you for merging!

I’m now trying to install docker (I have a little bit of free time right now) to be able to give this testing myself.

**Comment by juditacs** [comment]
It seems like the image fails to build, something wrong with PHP7 install. Things change in two years :D

**Comment by ArneBab** [comment]
yes … regular breakage through change is one of the banes of the current software infrastructure …

**Comment by juditacs** [comment]
especially when you install 10+ compilers

**Comment by ArneBab** [comment]
(which is the typical case on a Gentoo box ☺ — I’m running Gentoo and I have a special place reserved for haskell which almost always has breakage on updates)

**Comment by ArneBab** [comment]
You need sudo apt-get install guile-2.0

**Comment by ArneBab** [comment]
For me it works. Here’s some automatic plotting:

`cut -f 1-5 --output-delimiter=',' < results.txt > results-comma.txt`

Then in `gnuplot`

`set xtics rotate 90
set datafile separator ','`

And the plots:

`plot "< sort -ht, -k2 results-comma.txt" using 4:xticlabels(1) with boxes title "max memory"`

`plot "< sort -ht, -k2 results-comma.txt" using 2:xticlabels(1) with boxes title "CPU seconds", "< sort -ht, -k2 results-comma.txt" using 3:xticlabels(1) with boxes title "User time"`

**Comment by ArneBab** [comment]
To build guile 2.2.2:

`sudo apt-get install guile-2.0-dev libltdl-dev libunistring-dev pkg-config `

`wget https://ftp.gnu.org/gnu/guile/guile-2.2.2.tar.gz; tar xf guile-2.2.2.tar.gz; cd guile-2.2.2; ./configure --prefix=$HOME/.local --exec-prefix=$HOME/.local && make && make install`

**Comment by ArneBab** [comment]
When I run with 2.2.2, the first run is very slow, the second is about as fast as nodejs.

**Pull request merged**
