### PR TITLE
Add scala benchmark

### PR DESCRIPTION
**Pull request by hansbogert**

### CODE REVIEW

**Comment by juditacs** [comment]
Is there no way to install scala from the official repositories?

The build script should go back two directories:

    cd ../../scala

**Comment by hansbogert** [comment]
We could install from repo, but Scala 2.9 is pretty old. A lot of other benchmarks seem to download a recent version directly. Also the new ubuntu LTS is right around the corner, it seems silly to use  repo packages just because. I'd have to change code as well.

**Comment by juditacs** [comment]
Alright. Can you please fix the build script?

**Comment by hansbogert** [comment]
I think I already fixed that early on. I added an extra `cd ..` after Rust's  section.

**Comment by juditacs** [comment]
Sorry, I missed that.
Can you do another pull? I've just merged a PR and there is a conflict.

**Comment by hansbogert** [comment]
Conflict resolved

**Comment by juditacs** [comment]
Cool, thank you. A 5M test finishes in about 3 minutes:
scala -J-Xmx2g -classpath scala Wordcount       171.17  226.06  1421108

**Comment by hansbogert** [comment]
what is your reference system? Because in my case it's not significantly slower than ~2.5x C++

Are you running the complete benchmark in Docker? If so, is docker running natively, i.e. are you running docker on Linux?

**Comment by juditacs** [comment]
I'm running the whole test (I wouldn't call it a benchmark) in Docker which is running on a Linux host, which is a virtual machine.

What is your reference system?

**Comment by hansbogert** [comment]
Double checking the numbers, now also running in Docker, I'll update here.

**Comment by hansbogert** [comment]
btw, 5M lines of input? Mine is only 2.4M lines and is 122MB large. Downloaded with your `create_input.sh` script.

**Comment by juditacs** [comment]
That one downloads huwikisource but I added yesterday a [create_large_input.sh](https://github.com/juditacs/wordcount/blob/master/scripts/create_large_input.sh) which downloads the full Hungarian Wikipedia.

**Comment by hansbogert** [comment]
Aha that explains a lot :) Rerunning

**Comment by hansbogert** [comment]
Can you explain how you test? Are the result numbers you are using in the overview table in the README using the full dataset? The command you supply in the readme to test, 
`bash scripts/compare.sh data/huwikisource-latest-pages-meta-current.xml 2` is using the smaller one.

For example, on my system, the `cpp_vector` on the complete dataset uses more than 4GB of mem.

**Comment by juditacs** [comment]
This is the command I run:

    bash scripts/compare.sh data/huwiki-latest-pages-meta-current.xml  1 "full huwiki"

As of yesterday evening, these are the results:

| Rank | Experiment | CPU seconds | User time | Maximum memory |
| :---: | :---: | :---: | :---: | :---: |
| 1 | rust/wordcount/wordcount | 201.14 | 158.65 | 6867252 |
| 2 | cpp/wc_vector | 293.53 | 281.05 | 4186928 |
| 3 | go/bin/wordcount | 322.35 | 309.16 | 6084592 |
| 4 | python/wordcount_py2gabor.py | 329.32 | 315.91 | 3895348 |
| 5 | php7.0 php/wordcount.php | 455.05 | 353.92 | 4111164 |
| 6 | python/wordcount_py2.py | 532.92 | 515.44 | 8802352 |
| 7 | mono csharp/WordCountList.exe | 751.76 | 589.84 | 4785268 |
| 8 | perl/wordcount.pl | 860.05 | 837.29 | 7100120 |
| 9 | python/wordcount_py3.py | 906.21 | 881.89 | 7672796 |
| 10 | php5.6 php/wordcount.php | 1060.73 | 956.01 | 12672596 |
| 11 | julia julia/wordcount.jl | 1755.9 | 1717.57 | 7391812 |
| 12 | bash/wordcount.sh | 2486.98 | 2575.02 | 13768 |
| 13 | cpp/wc_baseline | 3204.84 | 3104.41 | 5965464 |

The leaderboard in the README is run on 5 million lines.
I haven't published the full leaderboard for several reasons. Hopefully I'll have time for it in the next couple days.

**Comment by hansbogert** [comment]
Sorry for dragging this on, but the numbers you provided me:

```
Cool, thank you. A 5M test finishes in about 3 minutes:
scala -J-Xmx2g -classpath scala Wordcount 171.17 226.06 1421108 
```
How can I mimic this? The huwikisource is smaller, and the full dataset is much larger than 5M

**Comment by juditacs** [comment]
You're absolutely right. I actually wrote a script to test just one command as I get many new ones and I really don't want to rerun everything every time. I'll add it shortly to the repo.

**Comment by juditacs** [comment]
~~~
scripts/run_one.sh <(head -5000000 data/huwiki-latest-pages-meta-current.xml ) "scala -J-Xmx2g -classpath scala Wordcount" "5M huwiki scala test"
~~~

This is the script I use. Arguments:

1. input
2. run command
3. comment (optional)
4. run N times (default=1)

**Comment by hansbogert** [comment]
Yeah works fine. Still within 2.5x C++. The JVM is to no surprise,  pretty important. Adding only 1 parameter like `-J-Xms1500m` (not in the repo currently) puts the scala implementation within 2.0x C++. The full dataset will undoubtly be far worse as the JVM will be capped at 2GB of memory, whilst I expect it to need close to 8GB.

**Comment by juditacs** [comment]
The current Java implementations actually choke on reading the full dataset. Let me know if you come up with a way to process the full huwiki.

**Pull request merged**
