### PR TITLE
Improvement(?) on PHP version: avoid copying the words array for sorting.

### PR DESCRIPTION
**Pull request by Coderdreams**
I thought this used half the memory of the original version, but later tests show me no memory improvement and a regression in CPU use. Maybe my virtual machine is acting up.

Could someone take a look and give it a run to see if there are any improvements?

### CODE REVIEW

**Comment by Coderdreams** [comment]
I finally confirmed there was no performance improvement with this so disregard this pull request.
I can say though that I tested PHP7's performance and it beats 5's by far, placing PHP in a much higher place in the score (faster than C#).
This object oriented version matches C#'s performance in PHP7 too, so it might be nice to have it around to compare how different language deal with a lot of objects.

**Comment by juditacs** [comment]
Thanks for your work.
You can add PHP7 install to the Dockerfile and have a separate test for PHP7 and 5. I'd happy to add another PHP version to the main repo.

**Comment by juditacs** [comment]
I finally got the test machine running again. Let me know if you have a test-ready version.

**Comment by Coderdreams** [comment]
Sure thing. Sorry I've been busy but I will try to make the changes ASAP.

**Comment by juditacs** [comment]
Can I close this now?

**Comment by Coderdreams** [comment]
Sure. Thank you!

**Pull request closed without merging**
